"""Pydantic models for the Apple Search Ads API.

This module exports all the data models used to interact with the
Apple Search Ads API. All models are Pydantic BaseModels with full
type hints and validation.
"""

from search_ads_api.models.ad_groups import (
    AdGroup,
    AdGroupCreate,
    AdGroupDisplayStatus,
    AdGroupServingStateReason,
    AdGroupServingStatus,
    AdGroupStatus,
    AdGroupUpdate,
    AutomatedKeywordsOptInStatus,
    CpaGoal,
    TargetingDimensions,
)
from search_ads_api.models.base import (
    Condition,
    ConditionOperator,
    Money,
    PageDetail,
    PaginatedResponse,
    Pagination,
    Selector,
    Sorting,
    SortOrder,
)
from search_ads_api.models.campaigns import (
    AdChannelType,
    BillingEvent,
    Campaign,
    CampaignCountryOrRegionServingStateReason,
    CampaignCreate,
    CampaignDisplayStatus,
    CampaignServingStateReason,
    CampaignServingStatus,
    CampaignStatus,
    CampaignSupplySource,
    CampaignUpdate,
)
from search_ads_api.models.keywords import (
    Keyword,
    KeywordCreate,
    KeywordMatchType,
    KeywordStatus,
    KeywordUpdate,
    NegativeKeyword,
    NegativeKeywordCreate,
)
from search_ads_api.models.reports import (
    GranularityType,
    ReportingRequest,
    ReportingResponse,
    ReportMetadata,
    ReportRow,
    SpendRow,
)

__all__ = [
    "AdChannelType",
    "AdGroup",
    "AdGroupCreate",
    "AdGroupDisplayStatus",
    "AdGroupServingStateReason",
    "AdGroupServingStatus",
    "AdGroupStatus",
    "AdGroupUpdate",
    "AutomatedKeywordsOptInStatus",
    "BillingEvent",
    "Campaign",
    "CampaignCountryOrRegionServingStateReason",
    "CampaignCreate",
    "CampaignDisplayStatus",
    "CampaignServingStateReason",
    "CampaignServingStatus",
    "CampaignStatus",
    "CampaignSupplySource",
    "CampaignUpdate",
    "Condition",
    "ConditionOperator",
    "CpaGoal",
    "GranularityType",
    "Keyword",
    "KeywordCreate",
    "KeywordMatchType",
    "KeywordStatus",
    "KeywordUpdate",
    "Money",
    "NegativeKeyword",
    "NegativeKeywordCreate",
    "PageDetail",
    "PaginatedResponse",
    "Pagination",
    "ReportMetadata",
    "ReportRow",
    "ReportingRequest",
    "ReportingResponse",
    "Selector",
    "SortOrder",
    "Sorting",
    "SpendRow",
    "TargetingDimensions",
]
